### ISSUE TITLE
检测速度很慢

### ISSUE THREAD

**Issue by kunyao2015** [enazoe/yolo-tensorrt#10]
使用yolov3-tiny 进行测试，GPU：1050 ，单张测试图片检测速度 竟然是12221ms， 明显感觉不对，是什么其他地方要注意吗？

Loading pre-trained weights...
Loading complete!
Using previously generated plan file located at ../configs/yolov3-tiny-kFLOAT.engine
Loading TRT Engine...
Loading Complete!
Label:2
className:car
Label:7
className:truck
Label:16
className:dog
detect time = 12221ms
id:2 prob:0.725098 rect:[220 x 89 from (466, 82)]
id:7 prob:0.584577 rect:[99 x 67 from (530, 94)]
id:16 prob:0.831854 rect:[257 x 299 from (124, 218)]

**Comment by enazoe** [comment]
@kunyao2015 这个可能是第一帧gpu cuda启动得问题，你试下多检测几张，第一帧后面得帧应该就正常了

**Comment by kunyao2015** [comment]
谢谢！

**Comment by enazoe** [comment]
@kunyao2015 如果觉得有用点个star 哈😄
