### ISSUE TITLE
fatal error: NvInfer.h: No such file or directory

### ISSUE THREAD

**Issue by Tengyun-Mo** [enazoe/yolo-tensorrt#106]
When I make this project, I got the error:
`fatal error: NvInfer.h: No such file or directory`
How to fix it ?Thanks

**Comment by enazoe** [comment]
check the install of tensorrt

**Comment by xielock** [comment]
I have met the same problem, and I fix this problem through editting the CMakeLists, adding one line:
**include_directories(/your_PATH/TensorRT-6.0.1.5/include/)**
