### ISSUE TITLE
Implementing of YoloV4

### ISSUE THREAD

**Issue by SeaStarLight** [enazoe/yolo-tensorrt#11]
I saw YoloV4 was published a few days ago. Could you implement YoloV4 to use it with TensorRT? 
Thank you for your time.

**Comment by enazoe** [comment]
@SeaStarLight I am working on it ,but since I am busy working these days, it will take some time to finish it. And welocom others PR.

**Comment by SeaStarLight** [comment]
Thank you @enazoe. Looking forward to your update.

**Comment by KelvinHuang666** [comment]
excepting your yolov4 project

**Comment by KelvinHuang666** [comment]
Expecting you support yolov4.
