### ISSUE TITLE
这个calibration_image_list_file_txt是干嘛用的，不设置可以吗？

### ISSUE THREAD

**Issue by xinsuinizhuan** [enazoe/yolo-tensorrt#127]
std::string calibration_image_list_file_txt = "configs/calibration_images.txt";

我看测试例子里面，就Config config_v4没设置，其他都设置了。其他不设置可以吗，是干嘛用的？

**Comment by enazoe** [comment]
INT8模式较准用的

**Comment by xinsuinizhuan** [comment]
有校准图片吗？校准是怎么个原理，为啥校准，比较小白，希望指导？

**Comment by enazoe** [comment]
#8

**Comment by xinsuinizhuan** [comment]
> 
> 
> #8

感谢。

**Comment by Lenan22** [comment]
Please refer to our open source quantization tool ppq, the quantization effect is better than the calibration of tensorrt, if you encounter issues, we can help you solve them.
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_OnnxParser.md
