### ISSUE TITLE
yolov5问题

### ISSUE THREAD

**Issue by xinsuinizhuan** [enazoe/yolo-tensorrt#128]
windows10 cuda11.0 cudnn和tensorrt都是对应版本
我之前使用其他版本yolov5时，可能模型转engine时，对应不同版本s m l等参数不一样，那我们这个只能是s模型吗？

**Comment by xinsuinizhuan** [comment]
另外，现在支持yolov5的 v4和v5版本吗？

**Comment by enazoe** [comment]
看readme
