### ISSUE TITLE
TRT8分支，yolov4-tiny bug、不支持yolov3-tiny

### ISSUE THREAD

**Issue by richjjj** [enazoe/yolo-tensorrt#145]
TRT8分支下，yolov4-tiny的官方模型能正常预测，但是自己训练模型预测结果为空（同一模型在tensort7下能正常识别）；yolov3-tiny转成trt engine会报错。

**Comment by enazoe** [comment]
@chongzhong trt8的代码现在不支持yolov3-tiny和yolov4-tiny

**Comment by richjjj** [comment]
@enazoe 谢啦
