### ISSUE TITLE
yolov4 inference speed is slow

### ISSUE THREAD

**Issue by Tristesse-stk** [enazoe/yolo-tensorrt#164]
Hi, thank you for sharing a great open source project about TensorRT.
There is a question after I run the sample_detector with yolov4 successfully.
The inference time I tested is longer than the time you mentioned in your benchmark.
My environment:
Jetson XAVIER NX
TensorRT7.1.3
cuda10.2
cudnn8.0.0
opencv4.1.1

My result table is below.
<html>
<body>

<span>

精度 | 图像尺寸 | 速度
-- | -- | --
FP32 | 416*416 | 180ms
FP16 | 416*416 | 90ms

</span>

</body>
</html>

It is seen that it is slower than yours.
![Image](https://user-images.githubusercontent.com/55178320/153114220-b79db3d0-5e4d-4976-a8e2-2ff4e1bc12fd.png)

If you can help me suggest some possible solutions, I will be very grateful and give you a star.

**Comment by enazoe** [comment]
@Tristesse-stk modify the power mode to 2 core 15W, and turbo the cpu

**Comment by Tristesse-stk** [comment]
Great！Your solution is helpful and the inference speed is as fast as yours.I just gave the star to your project.

**Comment by denred0** [comment]
Hi! Can you say how to "modify the power mode to 2 core 15W, and turbo the cpu". ?
RTX 2080 Ti
TensorRT 8.0.6
CUDA 11.3
cuDNN 8.2.1

Thank you!

**Comment by Tristesse-stk** [comment]
In the upper right corner of the interface.
![MODE_set](https://user-images.githubusercontent.com/55178320/153560582-2c4e5da4-c54b-456f-8700-353aca6a9238.png)

**Comment by Nuzhny007** [comment]
@denred0 but it works only for Nvidia Jetson

**Comment by denred0** [comment]
@Nuzhny007 Yes, I understood
