### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by npumazehong** [enazoe/yolo-tensorrt#18]
undefined symbol: _ZN8Detector6detectERKN2cv3MatERSt6vectorI6ResultSaIS5_EE
undefined symbol: _ZN8Detector4initERK6Config	

I could run your sample yesterday.But today when I ran this sample,the errors above happened.I try to solve it,but it always show these errors.I know that the undefined symbol happens in "detector_->init(config)" and "detector_->detect()".My device is Nvidia Xavier NX,and the os is Ubuntu 18.04 customed by Nvidia.

**Comment by enazoe** [comment]
@npumazehong ok，sorry，I will fix it soon

**Comment by npumazehong** [comment]
> @npumazehong ok，sorry，I will fix it soon

So，have you find the error of dynamic link absence? I could not sovle this problem myself. Could you help me fix it soon? Thanks

**Comment by enazoe** [comment]
@npumazehong I 'm so sorry, my nx was taken by a colleague，and only wait for him to return to check what went wrong. you could try comment this [line ](https://github.com/enazoe/yolo-tensorrt/blob/master/CMakeLists.txt#L26)and rebuild.

**Comment by npumazehong** [comment]
I'm glad to receive your letter.You are such a nice man. I have commentted that line,but it didn't work. I guess there is something wrong happens in linking dynamic libraries or the definition of Detector(YoloDetector) Class's method.&nbsp; &nbsp;I'm looking forward to your reply.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "enazoe"<notifications@github.com&gt;; 
发送时间: 2020年7月16日(星期四) 下午2:37
收件人: "enazoe/yolo-tensorrt"<yolo-tensorrt@noreply.github.com&gt;; 
抄送: "Zehong Ma"<770634926@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [enazoe/yolo-tensorrt] undefined symbol (#18)





 
@npumazehong I 'm so sorry, my nx was taken by a colleague，and only wait for him to return to check what went wrong. you could try comment this line and rebuild.

**Comment by enazoe** [comment]
@npumazehong give your wechat account :)

**Comment by npumazehong** [comment]
ma770634926




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "enazoe/yolo-tensorrt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 下午3:05
收件人:&nbsp;"enazoe/yolo-tensorrt"<yolo-tensorrt@noreply.github.com&gt;;
抄送:&nbsp;"Zehong Ma"<770634926@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [enazoe/yolo-tensorrt] undefined symbol (#18)





 
@npumazehong give your wechat account :)
