### ISSUE TITLE
About the detetction precision

### ISSUE THREAD

**Issue by guods** [enazoe/yolo-tensorrt#2]
@enazoe Did you evaluate the detection precision? Too much accuracy reduction compared to no acceleration.

**Comment by enazoe** [comment]
@guods Yes，I evaluate it my own simple dataset . It does not have significant performance reduction. But for the INT8 precision ,the calibration images best to cover all dataset . In other word, keep the sample diversity.

**Comment by guods** [comment]
@enazoe In order to avoid the inferences of calibration images,  I detected my dataset on FP16，the detection results are also poor .

**Comment by junhua-zhang** [comment]
@guods @enazoe Correct cv4 act for bottleneck_csp to leaky relu, and precision problem should be solved.

**Comment by guods** [comment]
@junhua-zhang thanks, I would like to test it.
