### ISSUE TITLE
m_ClassNames contains 240 elements

### ISSUE THREAD

**Issue by Nuzhny007** [enazoe/yolo-tensorrt#20]
Here: https://github.com/enazoe/yolo-tensorrt/blob/master/modules/yolo.cpp#L666
This loop calls 3 times and m_ClassNames containts 240 elements: 0, 1, 2, ..., 79, 0, 1, 2, ..., 79, 0, 1, 2, ..., 79
I advance add condition:
```
if (m_ClassNames.empty())
{
			for (int i=0;i< outputTensor.numClasses;++i)
			{
				m_ClassNames.push_back(std::to_string(i));
			}
}
```

**Comment by enazoe** [comment]
@Nuzhny007 yeah，welcome PR  :)

**Comment by Nuzhny007** [comment]
Here: https://github.com/enazoe/yolo-tensorrt/pull/21
