### ISSUE TITLE
Unable to open image : data/test/12/14.jpg

### ISSUE THREAD

**Issue by jameslele** [enazoe/yolo-tensorrt#32]
$ ./yolo-trt 
WARNING: couldn't find: data/test/07/0.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/1.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/2.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/3.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/4.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/5.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/6.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/7.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/8.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/9.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/10.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/11.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/12.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/13.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/14.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/15.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/16.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/17.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/18.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/19.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/20.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/21.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/22.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/23.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/24.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/25.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/26.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/27.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/28.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/29.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/07/30.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/0.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/1.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/2.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/3.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/4.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/5.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/6.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/7.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/8.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/9.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/10.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/11.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/12.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/13.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/14.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/15.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/16.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/17.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/18.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/19.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/20.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/21.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/22.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/23.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/24.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/25.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/26.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/27.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/28.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/29.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/08/30.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/0.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/1.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/2.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/3.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/4.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/5.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/6.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/7.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/8.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/9.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/10.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/11.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/12.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/13.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/14.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/11/15.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/0.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/1.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/2.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/3.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/4.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/5.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/6.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/7.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/8.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/9.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/10.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/11.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/12.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/13.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/14.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/12/15.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/0.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/1.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/2.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/3.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/4.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/5.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/6.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/7.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/8.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/9.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/10.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/11.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/12.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/13.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/14.jpg while loading: ../configs/calibration_images.txt
WARNING: couldn't find: data/test/13/15.jpg while loading: ../configs/calibration_images.txt
Loading pre-trained weights...
Loading complete!
      layer               inp_size            out_size       weightPtr
(1)   conv-bn-leaky     3 x 416 x 416      16 x 416 x 416    496   
(2)   maxpool          16 x 416 x 416      16 x 208 x 208    496   
(3)   conv-bn-leaky    16 x 208 x 208      32 x 208 x 208    5232  
(4)   maxpool          32 x 208 x 208      32 x 104 x 104    5232  
(5)   conv-bn-leaky    32 x 104 x 104      64 x 104 x 104    23920 
(6)   maxpool          64 x 104 x 104      64 x  52 x  52    23920 
(7)   conv-bn-leaky    64 x  52 x  52     128 x  52 x  52    98160 
(8)   maxpool         128 x  52 x  52     128 x  26 x  26    98160 
(9)   conv-bn-leaky   128 x  26 x  26     256 x  26 x  26    394096
(10)  maxpool         256 x  26 x  26     256 x  13 x  13    394096
(11)  conv-bn-leaky   256 x  13 x  13     512 x  13 x  13    1575792
(12)  maxpool         512 x  13 x  13     512 x  13 x  13    1575792
(13)  conv-bn-leaky   512 x  13 x  13    1024 x  13 x  13    6298480
(14)  conv-bn-leaky  1024 x  13 x  13     256 x  13 x  13    6561648
(15)  conv-bn-leaky   256 x  13 x  13     512 x  13 x  13    7743344
(16)  conv-linear     512 x  13 x  13     255 x  13 x  13    7874159
(17)  yolo            255 x  13 x  13     255 x  13 x  13    7874159
(18)  route                  -            256 x  13 x  13    7874159
(19)  conv-bn-leaky   256 x  13 x  13     128 x  13 x  13    7907439
(20)  upsample        128 x  13 x  13     128 x  26 x  26        - 
(21)  route                  -            384 x  26 x  26    7907439
(22)  conv-bn-leaky   384 x  26 x  26     256 x  26 x  26    8793199
(23)  conv-linear     256 x  26 x  26     255 x  26 x  26    8858734
(24)  yolo            255 x  26 x  26     255 x  26 x  26    8858734
File does not exist : ../configs/yolov3-tiny-kINT8.engine
Building the TensorRT Engine...
New calibration table will be created to build the engine
WARNING: Unable to open image : data/test/12/14.jpg
yolo-trt: /home/jiale/yolo-tensorrt/modules/ds_image.cpp:106: DsImage::DsImage(const string&, const int&, const int&): Assertion `0' failed.
Aborted (core dumped)

Where could I get data/test/...

**Comment by enazoe** [comment]
when the INT8 calibration ,you must prepare the calibration image subset of your train set.
