### ISSUE TITLE
fail to build yolov4 engine

### ISSUE THREAD

**Issue by liudakai2** [enazoe/yolo-tensorrt#36]
求助作者大大和各位大佬~
xavier上编译项目成功，但运行demo的时候报错：
modules/yolo.cpp:522: void Yolo::createYOLOEngine(nvinfer1::DataType, Int8EntropyCalibrator*): Assertion `m_Engine != nullptr' failed.

系统环境：
JetPack 4.3
Ubuntu 18.04.3 LTS
CUDA 10.0.326
cudnn 7.6.3
Tensorrt 6.0.1
OpenCV 4.1.1

**Comment by enazoe** [comment]
@liudakai2 你刷成jetpack4.4试试？

**Comment by liudakai2** [comment]
嗯嗯，我板子上还部署了其他东西，暂时不能刷成4.4，谢谢作者大大



---Original---

**Comment by enazoe** [comment]
@liudakai2 你回滚到之前的版本试下，yolov4用了些新的api，改下对应版本的api就行，类名相似

**Comment by liudakai2** [comment]
嗯嗯好的



---Original---
