### ISSUE TITLE
多线程会报Cuda Error in execute: 77 (an illegal memory access was encountered)错误

### ISSUE THREAD

**Issue by kunyao2015** [enazoe/yolo-tensorrt#37]
单线程调用正常，多线程调用时跑一会就会报类似Cuda Error in execute: 77 (an illegal memory access was encountered)的错误，错误处大约在yolo.cpp 中的Yolo::doInference
`NV_CUDA_CHECK(cudaMemcpyAsync(m_DeviceBuffers.at(m_InputBindingIndex), input,
                                  batchSize * m_InputSize * sizeof(float), cudaMemcpyHostToDevice,
                                  m_CudaStream));`
有遇到相关的问题吗？

**Comment by enazoe** [comment]
inference不支持多线程，你两个线程实例化两个模型试下
