### ISSUE TITLE
What is the usage of yoloplugin_lib and preprocess?

### ISSUE THREAD

**Issue by beizhengren** [enazoe/yolo-tensorrt#39]
Hi @enazoe ,
1. What is the usage of  **yoloplugin_lib.h**  and  **yoloplugin_lib.cpp**?
It seems for batch inference?

2. What's the preprocess code for yolov4 ?   

Thanks!

**Comment by enazoe** [comment]
@beizhengren 1.基本上是，已经被废弃了 。 2. 这个是相对于inference time来说的，就是在数据进入网络前对图像的处理都算，resize，归一化等

**Comment by beizhengren** [comment]
@enazoe 感谢!
最近在研究您的代码, 等您有空的话, 您看是否可以精简下代码^ ^
然后,有关预处理数据,我看您用的opencv的库, 这样就直接可以搞定吗?
https://github.com/enazoe/yolo-tensorrt/blob/1582df30e063b5b174e941abc6275d07b6468c82/modules/trt_utils.cpp#L44
谢谢!

**Comment by enazoe** [comment]
@beizhengren 嗯，后面会整理，那个函数是批量预处理的，具体的你可以查查opencv对它的说明

**Comment by beizhengren** [comment]
@enazoe 感谢!!

**Comment by beizhengren** [comment]
@enazoe 
作者您好, 
请问TensorRT的输入必须是NCHW的吗?

**Comment by enazoe** [comment]
@beizhengren 是的，bchw
