### ISSUE TITLE
About darknet cfg weights parse

### ISSUE THREAD

**Issue by beizhengren** [enazoe/yolo-tensorrt#42]
作者您好:
关于解析cfg和weights, 看您是自己写的函数, 
如果用darknetAB自己的`parse_network_cfg(...)`和`load_weights(...)`进行解析可以吗?您之前是如何考虑的呢?
谢谢!

**Comment by enazoe** [comment]
@beizhengren 这个其实都行，主要是看你后面怎么用方便就怎么组织数据，数据都一样，结构怎么组织其实都行

**Comment by beizhengren** [comment]
@enazoe 
恩恩,我理解了.
非常感谢!
