### ISSUE TITLE
关于yaml2cfg.py

### ISSUE THREAD

**Issue by lq0104** [enazoe/yolo-tensorrt#48]
您好，您提供的yaml2cfg.py转换后的cfg和weights模型是不是只能用于tensorRT的推理，是不能被AlexeyAB darknet的repo所训练的对吗

**Comment by enazoe** [comment]
@lq0104 是的，只是一种组织方式而已，是为trt服务的

**Comment by lq0104** [comment]
好的，明白了

**Comment by enazoe** [comment]
@lq0104 觉得能用的话，star下哈

**Comment by lq0104** [comment]
好的，已Star，如果您的yaml2cfg脚本能够支持darknet训练可能对于想使用darknet进行finetune，darknet和yolov5训练模型MAP/速度的比对以及终端部署更方便了哈 :)
