### ISSUE TITLE
关于input image是RGB or BGR

### ISSUE THREAD

**Issue by lq0104** [enazoe/yolo-tensorrt#49]
您好，还想请教一个问题，AlexeyAB darknet训练基于的格式是RGB格式，opencv默认读出来的格式是BGR格式，请问您的代码中对通道做了转换吗，还有图像归一化使用的mean和std都是多少呀

**Comment by enazoe** [comment]
做了转换，已经转成rgb了，归一化部分https://github.com/enazoe/yolo-tensorrt/blob/master/modules/yolo.cpp#L201

**Comment by lq0104** [comment]
好的，多谢解答
