### ISSUE TITLE
yolov5转换失败

### ISSUE THREAD

**Issue by ZuyongWu** [enazoe/yolo-tensorrt#62]
你好，我按照教程，一步一步将yolov5转化成tensorrt支持的引擎，步骤如下：
![11](https://user-images.githubusercontent.com/43801775/94368009-822ea200-0114-11eb-994f-beda53354f01.PNG)
![22](https://user-images.githubusercontent.com/43801775/94368024-9f637080-0114-11eb-8aad-8c76d8f282e2.PNG)
![2020-09-27 23-15-30屏幕截图](https://user-images.githubusercontent.com/43801775/94368593-75f81400-0117-11eb-96b9-ceebe5e8c292.png)

请问我该怎么解决，还是就是我觉得我有点不清楚我要怎么运行检测？？命令是什么？

**Comment by enazoe** [comment]
@ZuyongWu 在main函数里修改下，默认是v4
