### ISSUE TITLE
TensorFlow-Yolov3 > onnx > trt

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [enazoe/yolo-tensorrt#63]
Hi, 
    I am trying to convert TensorFlow-Yolov3  .ckpt or .pb weights to  .onnx and then to .trt engine.   and finally, run in Xavier NX for the interface. 

I am able to convert .pb to .onnx  but having problems converting .onnx to .trt engine.  Is there any method to convert .ckpt weights directly to .trt engine?   I am facing the following errors during conversion. 

+Is there any WeChat group? 

![webwxgetmsgimg](https://user-images.githubusercontent.com/28862708/95648103-5d203300-0b07-11eb-9113-91581f30db9f.jpeg)

**Comment by enazoe** [comment]
NO,we have qq group 1151955802，this project just support the darknet weights. 
And the problem is that you have a custom layer， the parser can not parse the custom layer.

**Comment by MuhammadAsadJaved** [comment]
@enazoe  OK. Thank you.  How to handle the custom layers parsing problem? Any method or suggestions?

**Comment by enazoe** [comment]
use the tensorrt api,write a plugin layer

**Comment by MuhammadAsadJaved** [comment]
OK. Thank you very much.
