### ISSUE TITLE
你好，请问一下，用int8精度的模式怎样使用？

### ISSUE THREAD

**Issue by 121649982** [enazoe/yolo-tensorrt#8]
需要自己加上些图像吗？

**Comment by enazoe** [comment]
@121649982 
`config.inference_precison = INT8;
config.calibration_image_list_file_txt = "../configs/calibration_images.txt";`
int8校准的时候需要一些图像，用calibration_image_list_file_txt指定图片的路径

**Comment by 121649982** [comment]
> @121649982
> `config.inference_precison = INT8; config.calibration_image_list_file_txt = "../configs/calibration_images.txt";`
> int8校准的时候需要一些图像，用calibration_image_list_file_txt指定图片的路径

请问一下，如果用自己训练的模型，这些图像可以是用于训练的吗？感谢

**Comment by enazoe** [comment]
@121649982 就是需要你训练darknet模型时候的图片作为trt校准的图片，不需要全部，一个子集就行，几百张

**Comment by 121649982** [comment]
@enazoe 好的，谢谢了

**Comment by enazoe** [comment]
@121649982 注意这个子集要是训练集的均匀采样，如果觉得还不错点个star。。。。

**Comment by 121649982** [comment]
好的，感谢，你的代码真的很赞，我在windows上跑起来了

**Comment by Stars-Chan** [comment]
在Linux上注意把calibration_images.txt文件里面的”\“换成”/“

**Comment by henbucuoshanghai** [comment]
慢着    为什么需要deepstream   ？   训练的代码在哪里呢  yolo345？

**Comment by wangxudong-cq** [comment]
> arknet模型时候的图片作为trt校准的
这个图片集是自动下载的？
还是需要自己去找？

**Comment by wangxudong-cq** [comment]
> @121649982 `config.inference_precison = INT8; config.calibration_image_list_file_txt = "../configs/calibration_images.txt";` int8校准的时候需要一些图像，用calibration_image_list_file_txt指定图片的路径

这个数据集是自动下载的吗？

**Comment by enazoe** [comment]
> > @121649982 `config.inference_precison = INT8; config.calibration_image_list_file_txt = "../configs/calibration_images.txt";` int8校准的时候需要一些图像，用calibration_image_list_file_txt指定图片的路径
> 
> 这个数据集是自动下载的吗？
https://github.com/enazoe/yolo-tensorrt/issues/8#issuecomment-607185879 
https://github.com/enazoe/yolo-tensorrt/releases/tag/calibration_images.txt

**Comment by wangxudong-cq** [comment]
@enazoe thank you!
I have copied the images from the Coco training dataset。
